import type { Task } from './types';

const now = new Date();
const y = now.getFullYear();
const m = now.getMonth();

function d(day: number): string {
  return new Date(y, m, day).toISOString().slice(0, 10);
}

export const MOCK_TASKS: Task[] = [
  // 工作 - 本月
  { id: 1, cat: 'project', subCat: null, parentId: null, title: '完成项目方案设计', meta: null, priorityLevel: 'urgent_important', deadline: d(5), startDate: null, endDate: null, time: '10:00', done: false, archived: false, longterm: false, reminder: true, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: d(1) + 'T08:00:00Z', updatedAt: d(1) + 'T08:00:00Z' },
  { id: 2, cat: 'project', subCat: null, parentId: null, title: '团队周会讨论', meta: null, priorityLevel: 'important', deadline: d(8), startDate: null, endDate: null, time: '14:00', done: false, archived: false, longterm: false, reminder: false, monthlyRepeat: true, archivedAt: null, completedAt: null, createdAt: d(1) + 'T08:00:00Z', updatedAt: d(1) + 'T08:00:00Z' },
  { id: 3, cat: 'project', subCat: null, parentId: null, title: '代码审查', meta: null, priorityLevel: 'urgent', deadline: d(10), startDate: null, endDate: null, time: '10:00', done: false, archived: false, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: d(2) + 'T08:00:00Z', updatedAt: d(2) + 'T08:00:00Z' },
  { id: 4, cat: 'project', subCat: null, parentId: null, title: '客户需求评审', meta: '准备PPT', priorityLevel: 'urgent_important', deadline: d(12), startDate: null, endDate: null, time: '15:00', done: false, archived: false, longterm: false, reminder: true, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: d(3) + 'T08:00:00Z', updatedAt: d(3) + 'T08:00:00Z' },
  { id: 5, cat: 'project', subCat: null, parentId: null, title: '修复登录Bug', meta: null, priorityLevel: 'urgent', deadline: d(7), startDate: null, endDate: null, time: null, done: true, archived: false, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: d(5) + 'T10:00:00Z', createdAt: d(1) + 'T08:00:00Z', updatedAt: d(5) + 'T08:00:00Z' },
  // 琐事 - 本月
  { id: 6, cat: 'other', subCat: 'quick-task', parentId: null, title: '取快递', meta: null, priorityLevel: 'normal', deadline: d(6), startDate: null, endDate: null, time: null, done: false, archived: false, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: d(4) + 'T08:00:00Z', updatedAt: d(4) + 'T08:00:00Z' },
  { id: 7, cat: 'other', subCat: 'study-improve', parentId: null, title: '学习英语打卡', meta: null, priorityLevel: 'normal', deadline: null, startDate: null, endDate: null, time: '07:00', done: false, archived: false, longterm: true, reminder: true, monthlyRepeat: true, archivedAt: null, completedAt: null, createdAt: d(1) + 'T08:00:00Z', updatedAt: d(1) + 'T08:00:00Z' },
  { id: 8, cat: 'other', subCat: 'long-term', parentId: null, title: '整理书架', meta: null, priorityLevel: 'normal', deadline: d(15), startDate: null, endDate: null, time: null, done: false, archived: false, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: d(5) + 'T08:00:00Z', updatedAt: d(5) + 'T08:00:00Z' },
  // 理财 - 本月
  { id: 9, cat: 'credit', subCat: null, parentId: null, title: '理财记账-周期复盘', meta: null, priorityLevel: 'important', deadline: null, startDate: null, endDate: null, time: null, done: false, archived: false, longterm: true, reminder: false, monthlyRepeat: true, archivedAt: null, completedAt: null, createdAt: d(1) + 'T08:00:00Z', updatedAt: d(1) + 'T08:00:00Z' },
  { id: 10, cat: 'credit', subCat: null, parentId: null, title: '信用卡还款', meta: '招行', priorityLevel: 'urgent_important', deadline: d(20), startDate: null, endDate: null, time: null, done: false, archived: false, longterm: false, reminder: true, monthlyRepeat: true, archivedAt: null, completedAt: null, createdAt: d(1) + 'T08:00:00Z', updatedAt: d(1) + 'T08:00:00Z' },
  // 学习 - 本月
  { id: 11, cat: 'study', subCat: null, parentId: null, title: '阅读《原则》', meta: null, priorityLevel: 'important', deadline: d(25), startDate: null, endDate: null, time: null, done: false, archived: false, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: d(1) + 'T08:00:00Z', updatedAt: d(1) + 'T08:00:00Z' },
  { id: 12, cat: 'study', subCat: null, title: 'TypeScript高级培训', meta: null, priorityLevel: 'normal', parentId: null, deadline: d(18), startDate: null, endDate: null, time: '19:00', done: false, archived: false, longterm: false, reminder: true, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: d(2) + 'T08:00:00Z', updatedAt: d(2) + 'T08:00:00Z' },
  // 逾期任务
  { id: 13, cat: 'project', subCat: null, parentId: null, title: '完成Q2 OKR', meta: null, priorityLevel: 'urgent_important', deadline: new Date(y, m - 1, 28).toISOString().slice(0, 10), startDate: null, endDate: null, time: null, done: false, archived: false, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: new Date(y, m - 1, 1).toISOString().slice(0, 10) + 'T08:00:00Z', updatedAt: new Date(y, m - 1, 1).toISOString().slice(0, 10) + 'T08:00:00Z' },
  { id: 14, cat: 'other', subCat: 'project-setup', parentId: null, title: '项目环境搭建', meta: null, priorityLevel: 'important', deadline: new Date(y, m - 1, 30).toISOString().slice(0, 10), startDate: null, endDate: null, time: null, done: false, archived: false, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: new Date(y, m - 1, 15).toISOString().slice(0, 10) + 'T08:00:00Z', updatedAt: new Date(y, m - 1, 15).toISOString().slice(0, 10) + 'T08:00:00Z' },
  // 跨期任务
  { id: 15, cat: 'project', subCat: null, parentId: null, title: '新版UI重构', meta: null, priorityLevel: 'urgent_important', deadline: null, startDate: new Date(y, m, -5).toISOString().slice(0, 10), endDate: d(15), time: null, done: false, archived: false, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: new Date(y, m, -5).toISOString().slice(0, 10) + 'T08:00:00Z', updatedAt: new Date(y, m, -5).toISOString().slice(0, 10) + 'T08:00:00Z' },
  { id: 16, cat: 'project', subCat: null, parentId: null, title: '用户调研报告', meta: null, priorityLevel: 'important', deadline: null, startDate: new Date(y, m, -3).toISOString().slice(0, 10), endDate: d(10), time: null, done: false, archived: false, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: new Date(y, m, -3).toISOString().slice(0, 10) + 'T08:00:00Z', updatedAt: new Date(y, m, -3).toISOString().slice(0, 10) + 'T08:00:00Z' },
  // 长期常驻
  { id: 17, cat: 'project', subCat: null, parentId: null, title: '迭代项目A-性能优化', meta: null, priorityLevel: 'important', deadline: null, startDate: null, endDate: null, time: null, done: false, archived: false, longterm: true, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: d(1) + 'T08:00:00Z', updatedAt: d(1) + 'T08:00:00Z' },
  { id: 18, cat: 'project', subCat: null, parentId: null, title: '迭代项目B-用户反馈', meta: null, priorityLevel: 'normal', deadline: null, startDate: null, endDate: null, time: null, done: false, archived: false, longterm: true, reminder: false, monthlyRepeat: false, archivedAt: null, completedAt: null, createdAt: d(1) + 'T08:00:00Z', updatedAt: d(1) + 'T08:00:00Z' },
  // 归档任务
  { id: 100, cat: 'project', subCat: null, parentId: null, title: '完成Q1复盘', meta: null, priorityLevel: 'important', deadline: new Date(y, m - 2, 28).toISOString().slice(0, 10), startDate: null, endDate: null, time: null, done: true, archived: true, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: new Date(y, m - 1, 1).toISOString().slice(0, 10), completedAt: new Date(y, m - 1, 1).toISOString().slice(0, 10) + 'T10:00:00Z', createdAt: new Date(y, m - 2, 1).toISOString().slice(0, 10) + 'T08:00:00Z', updatedAt: new Date(y, m - 1, 1).toISOString().slice(0, 10) + 'T08:00:00Z' },
  { id: 101, cat: 'other', subCat: null, parentId: null, title: '搬家整理', meta: null, priorityLevel: 'normal', deadline: new Date(y, m - 1, 15).toISOString().slice(0, 10), startDate: null, endDate: null, time: null, done: true, archived: true, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: new Date(y, m - 1, 16).toISOString().slice(0, 10), completedAt: new Date(y, m - 1, 16).toISOString().slice(0, 10) + 'T14:00:00Z', createdAt: new Date(y, m - 1, 1).toISOString().slice(0, 10) + 'T08:00:00Z', updatedAt: new Date(y, m - 1, 16).toISOString().slice(0, 10) + 'T08:00:00Z' },
  { id: 102, cat: 'credit', subCat: null, parentId: null, title: '3月信用卡还款', meta: null, priorityLevel: 'urgent_important', deadline: new Date(y, m - 2, 20).toISOString().slice(0, 10), startDate: null, endDate: null, time: null, done: true, archived: true, longterm: false, reminder: false, monthlyRepeat: false, archivedAt: new Date(y, m - 2, 21).toISOString().slice(0, 10), completedAt: new Date(y, m - 2, 21).toISOString().slice(0, 10) + 'T09:00:00Z', createdAt: new Date(y, m - 2, 1).toISOString().slice(0, 10) + 'T08:00:00Z', updatedAt: new Date(y, m - 2, 21).toISOString().slice(0, 10) + 'T08:00:00Z' },
];
